#!/usr/bin/bash

wallpaperDir=~/Pictures/Wallpapers/

wal -i $wallpaperDir
swaymsg output "*" bg "$(cat ~/.cache/wal/wal)" fill

echo "Wallpaper changed"

#
# FOOT
#
CONFIG_BASE=~/.config/foot/foot.base.ini
CONFIG_OUT=~/.config/foot/foot.ini
WAL_COLORS=~/.cache/wal/colors-foot.ini

# Merge my config with colours generated by pywall
cat "$CONFIG_BASE" "$WAL_COLORS" > "$CONFIG_OUT"
echo "foot config updated"

# 
# WAYBAR
#
CONFIG_BASE=~/.config/waybar/style.base.css
CONFIG_OUT=~/.config/waybar/style.css
WAL_COLORS=~/.cache/wal/waybar.css

# Merge
cat "$WAL_COLORS" "$CONFIG_BASE" > "$CONFIG_OUT"
echo "waybar config updated"
pkill waybar && waybar &


# 
# TOFI
#
CONFIG_BASE=~/.config/tofi/base-config
CONFIG_OUT=~/.config/tofi/config
WAL_COLORS=~/.cache/wal/tofi-colors

# Merge my config with colours generated by pywall
cat "$WAL_COLORS" "$CONFIG_BASE" > "$CONFIG_OUT"
echo "tofi config updated"

# 
# MAKO
#
CONFIG_BASE=~/.config/mako/config.base
CONFIG_OUT=~/.config/mako/config
WAL_COLORS=~/.cache/wal/colors-mako

# Merge
cat "$WAL_COLORS" "$CONFIG_BASE" > "$CONFIG_OUT"
echo "mako config updated"
pkill mako && mako &



echo "done :)"
