#!/usr/bin/env bash

## Change wallpaper and adjust colors via pywal
# pywal: https://github.com/dylanaraps/pywal

# By default, pull wpp from paintings folder,
# if arguments are given chose accordingly
wallpaperDir=$HOME/Pictures/Wallpapers/paintings/

case "$1" in
    "other")
        wallpaperDir="$HOME/Pictures/Wallpapers/other"
        ;;
    "photos")
        wallpaperDir="$HOME/Pictures/Wallpapers/camera/"
        ;;
    *)
        # Do nothing
        ;;
esac

# full path so bash can find it in other environments (pipx stuff)
$HOME/.local/bin/wal -i "$wallpaperDir"

# Change wallpaper and tell sway about it
swaymsg output "*" bg "$(cat $HOME/.cache/wal/wal)" fill

#
# FOOT
#
CONFIG_BASE=$HOME/.config/foot/foot.base.ini
CONFIG_OUT=$HOME/.config/foot/foot.ini
WAL_COLORS=$HOME/.cache/wal/colors-foot.ini
# Merge base config with colours generated by pywall
cat "$CONFIG_BASE" "$WAL_COLORS" > "$CONFIG_OUT"

# 
# WAYBAR
#
CONFIG_BASE=$HOME/.config/waybar/style.base.css
CONFIG_OUT=$HOME/.config/waybar/style.css
WAL_COLORS=$HOME/.cache/wal/waybar.css
cat "$WAL_COLORS" "$CONFIG_BASE" > "$CONFIG_OUT"
pkill waybar && waybar &    # reload waybar


# 
# TOFI (app launcher)
#
CONFIG_BASE=$HOME/.config/tofi/base-config
CONFIG_OUT=$HOME/.config/tofi/config
WAL_COLORS=$HOME/.cache/wal/tofi-colors
cat "$WAL_COLORS" "$CONFIG_BASE" > "$CONFIG_OUT"

# 
# MAKO (notification daemon)
#
CONFIG_BASE=$HOME/.config/mako/config.base
CONFIG_OUT=$HOME/.config/mako/config
WAL_COLORS=$HOME/.cache/wal/colors-mako
cat "$WAL_COLORS" "$CONFIG_BASE" > "$CONFIG_OUT"    # Merge
pkill mako && mako &                                # Restart


# 
# LIBREWOLF
#
CONFIG_BASE=$HOME/.librewolf/y5e01tzp.default-default/chrome/userChromeBase
CONFIG_OUT=$HOME/.librewolf/y5e01tzp.default-default/chrome/userChrome.css
WAL_COLORS=$HOME/.cache/wal/colors.css
cat "$WAL_COLORS" "$CONFIG_BASE" > "$CONFIG_OUT"

# Done :)
notify-send "Wallpaper changed" "colours updated"
